version: "3"

x-logging:
  &tag-json-logs
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  traefik:
    container_name: traefik
    image: traefik:2.5
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /homelab/config/traefik.yml:/etc/traefik/traefik.yml
      - "/homelab/certificates/${DOMAIN_DIRECTORY}/cert.pem:/etc/traefik/certs/\
        default.cert" # Cert uploaded from OPNsense
      - "/homelab/certificates/${DOMAIN_DIRECTORY}/key.pem:/etc/traefik/certs/d\
        efault.key" # Key uploaded from OPNsense
    networks:
      - homelab
    logging: *tag-json-logs

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.3
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - GF_LOG_MODE=console file
    expose:
      - 3000
    volumes:
      - grafana:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.erhbg.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - homelab
    logging: *tag-json-logs

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.31.1
    restart: unless-stopped
    depends_on:
      - cadvisor
      - node-exporter
    expose:
      - 9090
    volumes:
      - /homelab/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - homelab
    logging: *tag-json-logs

  node-exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.3.1
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - homelab
    logging: *tag-json-logs

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    networks:
      - homelab
    logging: *tag-json-logs

  loki:
    container_name: loki
    image: grafana/loki:2.4.1
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - /homelab/config/loki.yml:/etc/loki/local-config.yaml
      - loki:/data/loki
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -ingester.wal-enabled=false
    networks:
      - homelab
    logging: *tag-json-logs

  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.1
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /homelab/config/promtail.yml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - homelab
    logging: *tag-json-logs

networks:
  homelab:
    name: homelab
    external: true

volumes:
  grafana:
    name: grafana
  prometheus:
    name: prometheus
  loki:
    name: loki
